global.React = require 'react'
global._ = require 'lodash'
global._utilities = require '../frameworkCore/utilities.coffee'
global.ValidationError = require '../frameworkCore/ValidationError.coffee'
global.BaseClass = require '../frameworkCore/Base.coffee'
global.ObjectOrientedRecord = require '../frameworkCore/ObjectOrientedRecord.coffee'
global.ActionHandler = require '../frameworkCore/ActionHandler.coffee'
global.PublishSubscribe = require 'models/modules/pubSub.coffee'
